spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  #配置jdbc数据源

  #jsp 支持
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/

 #关闭默认模板引擎缓存
  thymeleaf:
    cache: false

    #enabled: false


mybatis:
  mapper-locations: classpath:/mapper/*.xml


server:
  port: 8888

#  servlet:
#    context-path: /
